### PR TITLE
Add JUnit5 test coverage and documentation

### LINKED ISSUE #8: Add JUnit 5 support test coverage and documentation
### Summary

The code should work for JUnit 5, but it has not been tested yet. It would be nice to have a few tests and an example in the documentation

### References

_No response_

### PR DESCRIPTION
**Pull request by kapishmalik**
@oleg-nenashev I have added existing example tests in JUnit 5.

Resolves #8

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Thank you! Since we have multiple examples now, it would be great to also add titles to JUnit4 and JUnit5 examples so that they are visible in the table of contents

**Comment by kapishmalik** [comment]
incorporated

**Review by oleg-nenashev — COMMENTED** [review]
It would be nice to also update the `### Using the test container in JUnit 4/5` section with the JUnit 5 example. Arguably, JUnit 5 should go first and be used as a default in all other documentation sections that do not require both JUnit 4 and JUnit 5 examples
`

**Review by oleg-nenashev — APPROVED** [review]
Thank you! I will see how to optimize the vertical size of the examples later, maybe with expandable sections. But it looks good content-wise

**Pull request merged**
